//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/InputAction/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""4f5a0777-a20f-485b-903a-268e6c78850b"",
            ""actions"": [
                {
                    ""name"": ""LeftClickInput"",
                    ""type"": ""Button"",
                    ""id"": ""d16828d3-fe38-4bb1-87be-2749b526d9fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceClickInput"",
                    ""type"": ""Button"",
                    ""id"": ""690b7a5e-a4c3-4ce0-b354-b97342a84aa8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""28745b83-29e0-434b-a251-c4a36c8dfad7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""LeftClickInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23ad3455-813d-4080-8f95-dd986c7b9aff"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""SpaceClickInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""b8c9ade1-cbb6-4a5a-b585-b9dbb018acc9"",
            ""actions"": [
                {
                    ""name"": ""ClickInput"",
                    ""type"": ""Button"",
                    ""id"": ""5b67379c-40c3-4a57-aa24-a1d2cc407c96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""14a56bbe-1e58-4f4a-9a49-d81862f0f4a4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""ClickInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MobileInput"",
            ""id"": ""bcd848a5-2819-4b9d-ac8f-d5466621d1b7"",
            ""actions"": [
                {
                    ""name"": ""TouchInput"",
                    ""type"": ""Button"",
                    ""id"": ""599be6fb-10de-4665-a687-ff306c22a546"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleTouchInput"",
                    ""type"": ""Button"",
                    ""id"": ""0647bae4-cd1d-4475-ad09-8e2b94888118"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89980631-0267-4606-a284-69502e339de1"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MOBILE"",
                    ""action"": ""TouchInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19cfcea2-f837-4ef0-b706-081d9e0e1f0a"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""MultiTap(tapTime=0.2,tapDelay=0.75,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": ""MOBILE"",
                    ""action"": ""DoubleTouchInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""MOBILE"",
            ""bindingGroup"": ""MOBILE"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LeftClickInput = m_Player.FindAction("LeftClickInput", throwIfNotFound: true);
        m_Player_SpaceClickInput = m_Player.FindAction("SpaceClickInput", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_ClickInput = m_UI.FindAction("ClickInput", throwIfNotFound: true);
        // MobileInput
        m_MobileInput = asset.FindActionMap("MobileInput", throwIfNotFound: true);
        m_MobileInput_TouchInput = m_MobileInput.FindAction("TouchInput", throwIfNotFound: true);
        m_MobileInput_DoubleTouchInput = m_MobileInput.FindAction("DoubleTouchInput", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_LeftClickInput;
    private readonly InputAction m_Player_SpaceClickInput;
    public struct PlayerActions
    {
        private @PlayerAction m_Wrapper;
        public PlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftClickInput => m_Wrapper.m_Player_LeftClickInput;
        public InputAction @SpaceClickInput => m_Wrapper.m_Player_SpaceClickInput;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @LeftClickInput.started += instance.OnLeftClickInput;
            @LeftClickInput.performed += instance.OnLeftClickInput;
            @LeftClickInput.canceled += instance.OnLeftClickInput;
            @SpaceClickInput.started += instance.OnSpaceClickInput;
            @SpaceClickInput.performed += instance.OnSpaceClickInput;
            @SpaceClickInput.canceled += instance.OnSpaceClickInput;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @LeftClickInput.started -= instance.OnLeftClickInput;
            @LeftClickInput.performed -= instance.OnLeftClickInput;
            @LeftClickInput.canceled -= instance.OnLeftClickInput;
            @SpaceClickInput.started -= instance.OnSpaceClickInput;
            @SpaceClickInput.performed -= instance.OnSpaceClickInput;
            @SpaceClickInput.canceled -= instance.OnSpaceClickInput;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_ClickInput;
    public struct UIActions
    {
        private @PlayerAction m_Wrapper;
        public UIActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClickInput => m_Wrapper.m_UI_ClickInput;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @ClickInput.started += instance.OnClickInput;
            @ClickInput.performed += instance.OnClickInput;
            @ClickInput.canceled += instance.OnClickInput;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @ClickInput.started -= instance.OnClickInput;
            @ClickInput.performed -= instance.OnClickInput;
            @ClickInput.canceled -= instance.OnClickInput;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // MobileInput
    private readonly InputActionMap m_MobileInput;
    private List<IMobileInputActions> m_MobileInputActionsCallbackInterfaces = new List<IMobileInputActions>();
    private readonly InputAction m_MobileInput_TouchInput;
    private readonly InputAction m_MobileInput_DoubleTouchInput;
    public struct MobileInputActions
    {
        private @PlayerAction m_Wrapper;
        public MobileInputActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchInput => m_Wrapper.m_MobileInput_TouchInput;
        public InputAction @DoubleTouchInput => m_Wrapper.m_MobileInput_DoubleTouchInput;
        public InputActionMap Get() { return m_Wrapper.m_MobileInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MobileInputActions set) { return set.Get(); }
        public void AddCallbacks(IMobileInputActions instance)
        {
            if (instance == null || m_Wrapper.m_MobileInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MobileInputActionsCallbackInterfaces.Add(instance);
            @TouchInput.started += instance.OnTouchInput;
            @TouchInput.performed += instance.OnTouchInput;
            @TouchInput.canceled += instance.OnTouchInput;
            @DoubleTouchInput.started += instance.OnDoubleTouchInput;
            @DoubleTouchInput.performed += instance.OnDoubleTouchInput;
            @DoubleTouchInput.canceled += instance.OnDoubleTouchInput;
        }

        private void UnregisterCallbacks(IMobileInputActions instance)
        {
            @TouchInput.started -= instance.OnTouchInput;
            @TouchInput.performed -= instance.OnTouchInput;
            @TouchInput.canceled -= instance.OnTouchInput;
            @DoubleTouchInput.started -= instance.OnDoubleTouchInput;
            @DoubleTouchInput.performed -= instance.OnDoubleTouchInput;
            @DoubleTouchInput.canceled -= instance.OnDoubleTouchInput;
        }

        public void RemoveCallbacks(IMobileInputActions instance)
        {
            if (m_Wrapper.m_MobileInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMobileInputActions instance)
        {
            foreach (var item in m_Wrapper.m_MobileInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MobileInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MobileInputActions @MobileInput => new MobileInputActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    private int m_MOBILESchemeIndex = -1;
    public InputControlScheme MOBILEScheme
    {
        get
        {
            if (m_MOBILESchemeIndex == -1) m_MOBILESchemeIndex = asset.FindControlSchemeIndex("MOBILE");
            return asset.controlSchemes[m_MOBILESchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnLeftClickInput(InputAction.CallbackContext context);
        void OnSpaceClickInput(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnClickInput(InputAction.CallbackContext context);
    }
    public interface IMobileInputActions
    {
        void OnTouchInput(InputAction.CallbackContext context);
        void OnDoubleTouchInput(InputAction.CallbackContext context);
    }
}
